package com.vip.wallet.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "SELECT_TOKEN".
*/
public class SelectTokenDao extends AbstractDao<SelectToken, Long> {

    public static final String TABLENAME = "SELECT_TOKEN";

    /**
     * Properties of entity SelectToken.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property ContractAddress = new Property(1, String.class, "contractAddress", false, "CONTRACT_ADDRESS");
        public final static Property Decimals = new Property(2, int.class, "decimals", false, "DECIMALS");
        public final static Property TokenName = new Property(3, String.class, "tokenName", false, "TOKEN_NAME");
        public final static Property IconUrl = new Property(4, String.class, "iconUrl", false, "ICON_URL");
        public final static Property FileName = new Property(5, String.class, "fileName", false, "FILE_NAME");
        public final static Property IsSelect = new Property(6, boolean.class, "isSelect", false, "IS_SELECT");
        public final static Property Balance = new Property(7, String.class, "balance", false, "BALANCE");
        public final static Property Amount_cny = new Property(8, String.class, "amount_cny", false, "AMOUNT_CNY");
        public final static Property Amount_usd = new Property(9, String.class, "amount_usd", false, "AMOUNT_USD");
        public final static Property Wallet_address = new Property(10, String.class, "wallet_address", false, "WALLET_ADDRESS");
    };


    public SelectTokenDao(DaoConfig config) {
        super(config);
    }
    
    public SelectTokenDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"SELECT_TOKEN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"CONTRACT_ADDRESS\" TEXT," + // 1: contractAddress
                "\"DECIMALS\" INTEGER NOT NULL ," + // 2: decimals
                "\"TOKEN_NAME\" TEXT," + // 3: tokenName
                "\"ICON_URL\" TEXT," + // 4: iconUrl
                "\"FILE_NAME\" TEXT," + // 5: fileName
                "\"IS_SELECT\" INTEGER NOT NULL ," + // 6: isSelect
                "\"BALANCE\" TEXT," + // 7: balance
                "\"AMOUNT_CNY\" TEXT," + // 8: amount_cny
                "\"AMOUNT_USD\" TEXT," + // 9: amount_usd
                "\"WALLET_ADDRESS\" TEXT);"); // 10: wallet_address
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"SELECT_TOKEN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, SelectToken entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String contractAddress = entity.getContractAddress();
        if (contractAddress != null) {
            stmt.bindString(2, contractAddress);
        }
        stmt.bindLong(3, entity.getDecimals());
 
        String tokenName = entity.getTokenName();
        if (tokenName != null) {
            stmt.bindString(4, tokenName);
        }
 
        String iconUrl = entity.getIconUrl();
        if (iconUrl != null) {
            stmt.bindString(5, iconUrl);
        }
 
        String fileName = entity.getFileName();
        if (fileName != null) {
            stmt.bindString(6, fileName);
        }
        stmt.bindLong(7, entity.getIsSelect() ? 1L: 0L);
 
        String balance = entity.getBalance();
        if (balance != null) {
            stmt.bindString(8, balance);
        }
 
        String amount_cny = entity.getAmount_cny();
        if (amount_cny != null) {
            stmt.bindString(9, amount_cny);
        }
 
        String amount_usd = entity.getAmount_usd();
        if (amount_usd != null) {
            stmt.bindString(10, amount_usd);
        }
 
        String wallet_address = entity.getWallet_address();
        if (wallet_address != null) {
            stmt.bindString(11, wallet_address);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, SelectToken entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String contractAddress = entity.getContractAddress();
        if (contractAddress != null) {
            stmt.bindString(2, contractAddress);
        }
        stmt.bindLong(3, entity.getDecimals());
 
        String tokenName = entity.getTokenName();
        if (tokenName != null) {
            stmt.bindString(4, tokenName);
        }
 
        String iconUrl = entity.getIconUrl();
        if (iconUrl != null) {
            stmt.bindString(5, iconUrl);
        }
 
        String fileName = entity.getFileName();
        if (fileName != null) {
            stmt.bindString(6, fileName);
        }
        stmt.bindLong(7, entity.getIsSelect() ? 1L: 0L);
 
        String balance = entity.getBalance();
        if (balance != null) {
            stmt.bindString(8, balance);
        }
 
        String amount_cny = entity.getAmount_cny();
        if (amount_cny != null) {
            stmt.bindString(9, amount_cny);
        }
 
        String amount_usd = entity.getAmount_usd();
        if (amount_usd != null) {
            stmt.bindString(10, amount_usd);
        }
 
        String wallet_address = entity.getWallet_address();
        if (wallet_address != null) {
            stmt.bindString(11, wallet_address);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public SelectToken readEntity(Cursor cursor, int offset) {
        SelectToken entity = new SelectToken( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // contractAddress
            cursor.getInt(offset + 2), // decimals
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // tokenName
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // iconUrl
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // fileName
            cursor.getShort(offset + 6) != 0, // isSelect
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // balance
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // amount_cny
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // amount_usd
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10) // wallet_address
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, SelectToken entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setContractAddress(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setDecimals(cursor.getInt(offset + 2));
        entity.setTokenName(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setIconUrl(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setFileName(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setIsSelect(cursor.getShort(offset + 6) != 0);
        entity.setBalance(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setAmount_cny(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setAmount_usd(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setWallet_address(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(SelectToken entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(SelectToken entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
